backend:
  name: git-gateway
  branch: main # Double check if your branch is 'main' or 'master'

media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    format: "yaml-frontmatter"
    extension: "md"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price (KES)", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Product Image", name: "image", widget: "image" }
